spring.application.name=portal
spring.datasource.url=jdbc:mysql://localhost:3306/PractiseJPA
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=mySecretKeyForJWTTokenGenerationWhichIsLongEnough
jwt.expiration=3600000